### ISSUE TITLE
Update npmjs package for version 0.5

### ISSUE THREAD

**Issue by anx-ckreuzberger** [cjroth/gulp-filelist#12]
Hi,

I've installed gulp-filelist using npm, where [npm uses version 0.4](https://www.npmjs.com/package/gulp-filelist) of your library.
Unfortunately, this version does not contain the latest fix (where you removed the `this.push(file);`, which is something I need.

For now, I helped myself by downloading and installing this package directly from github, using

``` bash
npm install git://github.com/cjroth/gulp-filelist.git
```

Though for future purpose it would be nice if the package on npmjs is updated.
Thanks!

**Comment by cjroth** [comment]
Thanks for reminding me. Just published 0.5.0 to fix this - should be good now :)
