### ISSUE TITLE
Creating custom json output?

### ISSUE THREAD

**Issue by CGTS** [cjroth/gulp-filelist#19]
Is it possible to achieve the following with gulp-filelist?

If I have a folder structure like:

```
pages/
├── lesson01/
│   ├── 01_001
│   ├── 01_002
├── lesson02/
│   ├── 02_001
│   ├── 02_002
```

How can I output a json file like this:

```
{
  "lesson01": [
    "01_001",
    "01_002"
  ],
  "lesson02": [
    "02_001",
    "02_002"
  ]
}
```

Any help is appreciated.

**Comment by cjroth** [comment]
Hey no unfortunately that is not possible, but PRs are welcome.
