### ISSUE TITLE
Output as dependency

### ISSUE THREAD

**Issue by ahudson87** [cjroth/gulp-filelist#24]
I'm trying to configure another task to consume the file output but cannot seem to get the dependency behavior I'm looking for. So far I haven't been able to determine if this is an issue with my configuration or understanding of gulp itself or the plugin usage.

I have a task creating the list
```
gulp.task('audit', function(){
    const pagefiles = [
        path.join(config.paths.src, '/hbs/pages/**/*.hbs'),
        path.join(config.paths.src, '/js/**/*.js'),
        "!" + path.join(config.paths.src, '/js/_modules/*.js'),
        path.join(config.paths.src, '/scss/**/*.scss'),
        "!" + path.join(config.paths.src, '/scss/_partials/*.scss')
    ];

    return gulp.src(pagefiles)
    .pipe(filelist('filelist.json', { relative: true }))
    .pipe(gulp.dest(config.paths.tmp));
});
```

The sequential task:
```
gulp.task('pages', ['audit'], function(){
    console.log('###########################################');
    console.log('Audited ' + files.length + ' files in source folders');
    console.log('###########################################');

    ....
});
```
...errs as the target JSON doesn't exist. Shouldn't 'pages' be waiting for filelist.json? Any insight would be greatly appreciated.

Thanks-

**Comment by cjroth** [comment]
Hard to tell just by looking at that code snippet. Yeah, `pages` should wait for `audit`. I wonder if it's somehow writing the file async without waiting before it resolves the promise. I'd also check to make sure the paths are correct and that the file is getting written correctly.

Gulp handles saving the file, not this plugin. But this is only 65 lines of code, so you could probably debug pretty easily :)

If there is a bug, feel free to submit a PR!

**Comment by ahudson87** [comment]
Thanks Chris-

I can confirm that the paths are correct. The output file writes properly, and if I run the task again it works, but it's always behind (if there is a change to filelist, `pages` doesn't see it until I run yet again- so it's never reliable).

I haven't had any luck debugging myself yet. Likely as you've said, if gulp is handling the file save it's probably not a bug in the plugin. I'm just not quite sure where to turn.

Anyway thanks for your response-

**Comment by cjroth** [comment]
No problem, good luck and let me know when you figure it out!

**Comment by ahudson87** [comment]
Actually I think I figured it out. Had to do with how/when I was requiring the external file. Plugin seems to be working exactly as expected. Very helpful tool for my use case! Thanks!

**Comment by cjroth** [comment]
:)
