### ISSUE TITLE
Support removing extension

### ISSUE THREAD

**Issue by FlorianWendelborn** [cjroth/gulp-filelist#6]
I'd like to use this to make a list of valid keys in a path which is like this: `presets/#nameIActuallyWant#.json`. `flatten` takes care of the `presets/` part, but it would be awesome if this module could also take care of removing the extension.

**Comment by cjroth** [comment]
I'd be happy to merge this if you submit a PR.

**Comment by FlorianWendelborn** [comment]
Why close the issue before it's actually fixed/implemented? Just because you don't want to do it yourself (which I can understand) doesn't mean the issue should be closed.

**Comment by cjroth** [comment]
Because it's not broken, it's just a new feature. You can submit a PR and I'll merge it.
